# Generated by Django 5.2.1 on 2025-05-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='people', max_length=30),
        ),
    ]
